services:
  - type: web
    name: task-manager-api
    runtime: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/task-manager-1.0.0.jar
    plan: free
    branch: master
